kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "trivy-scanner.fullname" . }}-trivy-scanner-config
data:
  config.yaml: |-
    configVersion: v1
    schedule:
    - name: scan
      crontab: "{{ .Values.schedule }}"
      allowFailure: true