apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trivy-scanner
    {{- include "trivy-scanner.labels" . | nindent 4 }}
  name: {{ include "trivy-scanner.fullname" . }}-trivy-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-scanner
      {{- include "trivy-scanner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: trivy-scanner
        {{- include "trivy-scanner.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/port: "9115"
        prometheus.io/scrape: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "trivy-scanner.serviceAccountName" . }}-trivy-scanner
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.githubToken.enabled -}}
        env:
        - name: GITHUB_TOKEN
          value: "{{ .Values.githubToken.token }}"
{{- end }}
        volumeMounts:
        - name: operator-config
          mountPath: /etc/trivy-scanner/
        - name: cache
          mountPath: "/home/kube-trivy-exporter/trivy-cache"
{{- if .Values.privateRegistry.enabled -}}
        - name: config-json
          mountPath: "/home/kube-trivy-exporter/.docker"
{{- end }}
        ports:
          - containerPort: 9115
      volumes:
      - configMap:
          name: {{ include "trivy-scanner.fullname" . }}-trivy-scanner-config
        name: operator-config
      - name: cache
        persistentVolumeClaim:
            claimName: {{ include "trivy-scanner.fullname" . }}-trivy-cache
{{- if .Values.privateRegistry.enabled -}}
      - name: config-json
        secret:
          secretName: {{ .Values.privateRegistry.secretNmae }}
{{- end }}