apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivy-scanner.fullname" . }}-trivy-scanner
  labels:
    app: trivy-scanner
    {{- include "trivy-scanner.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      targetPort: TCP
      port: {{ .Values.monitoring.port }}
      targetPort: 9115
  selector:
    app: trivy-scanner
    {{- include "trivy-scanner.selectorLabels" . | nindent 4 }}