# Default values for kube-openid-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

TimeZone: Europe/Budapest

server:
  debug: false
  oidcRedirectUrlHttpScema: http
  # redirect after logout
  oidcOutURL: https://devopstales.github.io/tags/kube-openid-connect/
  # http or https
  oidcRedirectUrlHost: chart-example.local
  # same es ingres host
  oidcServerURL:
  oidcClientID:
  oidcSecret:
  k8sContext:
  k8sApiServer:
  # `k8sApiServer` is the url for kubectl
  #   This is typically  https://api.fqdn
  k8sCaCrt: |-
    -----BEGIN CERTIFICATE-----
    CA
    -----END CERTIFICATE-----
# `caCrt` is the public / CA cert for the cluster
# cat /etc/kubernetes/pki/apiserver.crt

image:
  repository: devopstales/kube-openid-connector
  tag: "1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
#  - neme: 
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: ca-issuer
    # nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    # ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
