image:
  repository: devopstales/trivy-scanner
  pullPolicy: Always
  tag: "2.1"

imagePullSecrets: []
podSecurityContext:
  fsGroup: 10001

serviceAccount:
  create: true
  annotations: {}
  name: "trivy-scanner"

monitoring:
  port: "9115"

serviceMonitor:
  enabled: false
  namespace: "kube-system"

storage:
  enabled: true
  size: 1Gi

schedule: "*/5 * * * *"

privateRegistry:
  enabled: false
  secretName: ""

githubToken:
  enabled: false
  token: ""
