---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "logrotate.labels.chart" . | indent 6 }}
  name: {{ include "logrotate.name" . }}-config
data:
  k8s-logrotate.conf:  |-
{{ .Values.logrotateConfig | indent 6 }}
