apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trivy-image-validator.fullname" . }}-trivy-validation
  labels:
    app: trivy-validation
    {{- include "trivy-image-validator.labels" . | nindent 4 }}
  namespace: validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-validation
      {{- include "trivy-image-validator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: trivy-validation
        {{- include "trivy-image-validator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: cache
            mountPath: "/home/kube-trivy-admission/.cache/trivy"
{{- if .Values.privateRegistry.enabled -}}
          - name: config-json
            mountPath: "/home/kube-trivy-admission/.docker"
{{- end }}
      volumes:
      - name: cache
        persistentVolumeClaim:
            claimName: {{ include "trivy-image-validator.fullname" . }}-trivy-cache
{{- if .Values.privateRegistry.enabled -}}
      - name: config-json
        secret:
          secretName: {{ .Values.privateRegistry.secretName }}
{{- end }}
