apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ include "trivy-image-validator.fullname" . }}-trivy-cache
  namespace: validation
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: {{ .Values.storage.size }}