{{- if .Values.createSelfSignedCert }}
{{- $ca := .ca | default (genCA (printf "*.%s.svc" (include "trivy-image-validator.namespace" .)) 3650) -}}
{{- $altNames := list 
( printf "%s" ( include "trivy-image-validator.serviceName" .)) 
( printf "%s.%s" ( include "trivy-image-validator.serviceName" .) (include "trivy-image-validator.namespace" .)) 
( printf "%s.%s.svc" ( include "trivy-image-validator.serviceName" .) (include "trivy-image-validator.namespace" .)) 
-}}
{{- $cert := genSignedCert (printf "%s.%s.svc" (include "trivy-image-validator.serviceName" .) (include "trivy-image-validator.namespace" .)) nil $altNames 3650 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/allow-direct-injection: "true"
  name: {{ template "trivy-image-validator.serviceName" . }}.{{ template "trivy-image-validator.namespace" . }}.svc.tiv-tls-ca
  namespace: {{ template "trivy-image-validator.namespace" . }}
  labels: {{ include "trivy-image-validator.labels" . | nindent 4 }}
    app: trivy-validation
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.key: ""
  tls.crt: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trivy-image-validator.serviceName" . }}.{{ template "trivy-image-validator.namespace" . }}.svc.tiv-tls-pair
  namespace: {{ template "trivy-image-validator.namespace" . }}
  labels: {{ include "trivy-image-validator.labels" . | nindent 4 }}
    app: trivy-validation
  annotations:
    self-signed-cert: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
{{- end -}}