{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trivy-image-validator.serviceAccountName" . }}-trivy-validation
rules:
- apiGroups:
   - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trivy-image-validator.serviceAccountName" . }}-trivy-validation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "trivy-image-validator.serviceAccountName" . }}-trivy-validation
subjects:
- kind: ServiceAccount
  name: {{ include "trivy-image-validator.serviceAccountName" . }}-trivy-validation
  namespace: {{ template "trivy-image-validator.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trivy-image-validator.serviceAccountName" . }}-trivy-validation
  labels:
    app: trivy-validation
    {{- include "trivy-image-validator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}