apiVersion: v1
kind: Service
metadata:
  name: {{ template "trivy-image-validator.serviceName" . }}
  namespace: {{ template "trivy-image-validator.namespace" . }}
spec:
  selector:
    app: trivy-validation
    {{- include "trivy-image-validator.labels" . | nindent 4 }}
  ports:
  - port: 443
    targetPort: 5000
  selector:
    {{- include "trivy-image-validator.selectorLabels" . | nindent 4 }}