apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "trivy-image-validator.fullname" . }}-trivy-scanner
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-delete
webhooks:
  - name: trivy-scanner.devopstales.intra
    sideEffects: "None"
    admissionReviewVersions: [v1beta1, v1]
    clientConfig:
      service:
        name: trivy-scanner
        namespace: validation
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV6RENDQXJRQ0NRQ3JlR0l2WU9zS2RqQU5CZ2txaGtpRzl3MEJBUXNGQURBbk1TVXdJd1lEVlFRRERCeEIKWkcxcGMzTnBiMjRnUTI5dWRISnZiR3hsY2lCWFpXSm9iMjlyTUNBWERUSXhNRGN5TkRFNU1qRXpNRm9ZRHpJeApNakV3TmpNd01Ua3lNVE13V2pBbk1TVXdJd1lEVlFRRERCeEJaRzFwYzNOcGIyNGdRMjl1ZEhKdmJHeGxjaUJYClpXSm9iMjlyTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF5ZDZ3OXpaMjNHMk4KMk5Fdml2cjdxTVZXMllQcGdTZHJFbGJkMmtXRk5lbEFwL1ZFM3hVRG5FUXZ1bm5UMEJ4bUw0ckRmSzNBYmtvcQpXbzN0UjlUaDJFbzRnMTVQMC82NFhYak90MHJFbkp6RERIS2hkQzUraFVIUitkaEJuN3VhY1NYQzVqcEFyTDlXCi94Vy9nT0VRM05vTWUranZxWUYyT2MyeFZYd1czTEZDTmpLbEFOZFdIeC82QTI0QlYxZis3OXd0Y0oyZzhYR0EKWVR4cEJoZExsKzFYTGxhS2MraSs2NDh2LzBwYXdFVFoxSGVDeHVwVnFSZzV0dWVVWVRuTitXVWdIVzFVK0lBawpNVnV4Q3NpdXlRY3ZiVnljWjJaL2ZnSCtPVjZzTXd6VlErYVpKc0p1NVFTZHlVcHNIcXdjdW5ENzdCb1NUOVd1ClplZFBKQW5FS2VrVWowSlJhOXZuamRtTWxmSnpMMlFjWnB2Vll3RDlSODNRQkJNcks4QlVoMVFNOTRtMmlqYisKWDFmVjdTWEljdEdZQzJNTENINHkyQmFTOCtOdWhPS1dYdkN4V0Zaa2E2MEY1bTdnMEVLS2FSbkFVTGhPUDZpRAozVU4xV3M5Um1SSjVEdjN3WDNLaXJ5WlpCZ3cxeTlsU3hCNmsvM2FybmJwVW5paWptVVBvTUpqTms0Yy9oUXg1CkNIUFZPWHpvRlVjMmVyUm0rMzFZZ3dHaUhLd3FzeVlTOGNlQVI4VnpJSmppN1R3NWVERjBHQ1VOUVp6d0h0cEkKVU4wTnpZQnRLVk5NSXVHSmRZQVl3a3ZWakIxSkptY2JFOENCWERSWUkyTFVPYWUvRk43VDVaVW92RWw5QWUrZAp4NHRNd0ZVTEtRT1VEcnhXelFjcVgxanRNbVhsc1RVQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBCm5SRWRRdXoxSzF6eTRFbjQ4VXVnMFpubjhSM3hhYUNJWEpmaXRqZGxYbGFtTFNINXBVWWVpTXg5NWRIbklFdWUKNlRFZjQ4Q01GdmNPODJHeVQ5TGt3eVJwMmFyaGlzeUpSekVtaE9ZSmVUK3dYVWlVZ29hK2drUmFkM0EzMy9DVQpoTCt6bjVCOFF5N3dZWWY2QXpnV004N28vVkdGV3hmL1FjZmt0WUhYMTZCWExFK1E0MTJZd2lRQUE1VGs3dGt5Cm1vQS9vY0dDSFEvaE56K01qNWs4SlYrYTFTRVNXbmlFeGk2K01yaFFuZmhlWXJwNHJhUXJoWktVdmZ3NDE3Yk4KK1lucjFqWFY4ODZlK3ZxQzZucmxaK1UzTkU4OWpWN3Mycm9mVDNDdk8xNWk5R0Q2V0lUMEtuODQ0dThVc0EvLwppa2tsZkY4bUFxT0pVMkhuN2JlaUNuMlNPQWxITGEwcUVlKy9URzE1ckNTNlA5KzZka3VvSXE3K0RuQUFDck1SCnBLOEVMbzlDTENZT3lWRVFGR0o3TlcvdXlTNXVsMUMxNGRLeDdVTWdMaktaYVdLc3B3WmdYQmN5cUJqT1luc2kKOGlCblRkYnQ0RjlmKzZhN0FrOE93cXExZzN1cHlJMzdqTzN0Um1HQ2NBMWRtQUlIeWNRYjVBYll2UUtkRUdSSApub2pJS3A3bGxqQnUzWWRVN0JvQUZWL3hMUytzVkkwL0pUVmF4R3JrZHBtUlpJc2p2WGNkUWxPamszVEs2d05hCmRpMGlxUTFkZWhQNFk3bE9yME5zZm1QNkIxS2xxUzZ3U2wycU9ZbmhzcSttN2NGNlNCRmo4ZEpDNUxQSmlzOXAKWUdvb1h4M1EyeGpHVy9CQkM5WkFzUHlROGNpQlVKUFI2OTJYYjUzMlRLcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - apiGroups: ["apps", ""]
        resources:
          - "pods"
        apiVersions:
          - "*"
        operations:
          - CREATE
    namespaceSelector:
      matchLabels:
        trivy-image-validator: enabled