metricsPort: 10257
component: kube-controller-manager
clients:
  port: 10011
  useLocalhost: true
  https:
    enabled: true
    useServiceAccountCredentials: true
    insecureSkipVerify: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
  - effect: "NoExecute"
    operator: "Exists"
  - effect: "NoSchedule"
    operator: "Exists"
