image:
  repository: devopstales/trivy-scanner-admission
  pullPolicy: Always
  tag: "1.0.2"

imagePullSecrets: []
podSecurityContext:
  fsGroup: 10001

storage:
  enabled: true
  size: 1Gi

privateRegistry:
  enabled: false
  secretNmae: ""