{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ include "trivy-operator.fullname" . }}-trivy-cache
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: {{ .Values.storage.size }}
{{- end }}
