name: release
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@v2

#      - name: Publish Helm charts
#        uses: stefanprodan/helm-gh-pages@master
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          chart-search-root: charts

      - name: add repos
        run: |
          git config --global user.email "42894256+devopstales@users.noreply.github.com"
          git config --global user.name "devopstales"
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ubernetes-sigs https://kubernetes-sigs.github.io/metrics-server/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          mark_as_latest: false
          skip_existing: false
          packages_with_index: true
          charts_dir: charts
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
